export const SET_POPULAR_TV_SHOWS = 'SET_POPULAR_TV_SHOWS';
export const SET_TOP_RATED_TV_SHOWS = 'SET_TOP_RATED_TV_SHOWS';
export const SET_AIRING_NOW_TV_SHOWS = 'SET_AIRING_NOW_TV_SHOWS';
export const SET_LATEST_TV_SHOWS = 'SET_LATEST_TV_SHOWS';
