export const SET_MOVIE = "SET_MOVIE";
export const SET_CLEAR_MOVIE = "SET_CLEAR_MOVIE";
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_TOP_RATED_MOVIES = "SET_TOP_RATED_MOVIES";
export const SET_UPCOMING_MOVIES = "SET_UPCOMING_MOVIES";
export const SET_NOW_PLAYING_MOVIES = "SET_NOW_PLAYING_MOVIES";
