export const SET_MOVIES_IN_THEATRES = 'SET_MOVIES_IN_THEATRES';
export const SET_TV_SHOWS_AIRING_NOW = 'SET_TV_SHOWS_AIRING_NOW';
export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
export const SET_TOP_RATED_TV_SHOWS = 'SET_TOP_RATED_TV_SHOWS';
