export const SET_IS_MOBILE_SETTINGS_NAV_OPEN = "SET_IS_MOBILE_SETTINGS_NAV_OPEN"
export const SET_IS_DARK_THEME = "SET_IS_DARK_THEME"
export const SET_IS_MOBILE_SEARCH_BAR_OPEN = "SET_IS_MOBILE_SEARCH_BAR_OPEN"
