export const SET_MOVIES = "SET_MOVIES";
export const SET_MOVIES_ON_SCROLL = "SET_MOVIES_ON_SCROLL";
export const SET_TV_SHOWS = "SET_TV_SHOWS";
export const SET_TV_SHOWS_ON_SCROLL = "SET_TV_SHOWS_ON_SCROLL";
export const CLEAR_MOVIES = "CLEAR_MOVIES";
export const CLEAR_TV_SHOWS = "CLEAR_TV_SHOWS";
